Logo.all.delete_all

companies = [
    "GROUPE RENEW EUROPE",
    "FAM Pierre Bonhomme",
    "Clinique Alleray-Labrouste",
    "Clinique Rochebrune",
    "Hopital Bichat AP-HP",
    "Clinique Saint Christophe",
    "Maisons de Famille Villa concorde",
    "Hopital prive du val dyerres",
    "Foyer Notre Dame Association",
    "Centre Medical et de Readaptation des Monts Toulonnais",
    "Centre de Gerontologie Henry Dunant - MCO SSR Croix-Rouge francaise",
    "SSR Korian Val de Seine",
    "institut readaptation de Romainville",
    "Clinique SSR Sainte-Therese",
    "CMPR BOBIGNY",
    "Maison de Clervant",
    "REPOTEL Voisins-le-Bretonneux",
    "Clinique Jeanne darc",
    "Clinique Arago Paris - Chirurgie orthopedique et traumatologique",
    "Maisons de Famille Villa Lecourbe",
    "EHPAD Champsfleur",
    "EEAP Christian LAZARD",
    "Hopital de Jour LEtincelle",
    "THI FACTORY",
    "Masteos",
    "Stephane Sejourne - President du groupe Renew Europe",
    "Sthree",
    "ALTAVIA CONNECT",
    "Camille MALIS",
    "Swile",
    "FREE NOW for Business",
    "Victor and Simon",
    "Kokoon",
    "AGICAP",
    "Sthree ",
    "Societe Generale",
    "Geraldine Barthe Pouget",
    "Alessandro Di Nitto",
    "Ledger",
    "Summum 3D",
    "Ludovic Milon",
    "Marjorie Yung",
    "DJEREHE JONATHAN",
    "AVA2i",
    "LOreal",
    "Gie Pricewaterhousecoopers Services",
    "Altavia.Disko",
    "Charlotte David",
    "thomas-leduc.io",
    "Melody Acquaviva",
    "Christian SHUNGI",
    "MARCEL SMD",
    "Dominique Guerrand",
    "Lucie Grelier",
    "SThree",
    "Television Francaise 1 - TF1",
    "LOreal",
    "STHREE",
    "Bouygues Construction - IT BYCN",
    "Marion Tracanelli",
    "Proprioo",
    "Jean-Charles Cenci",
    "Kate Benson",
    "Sid Lee Paris",
    "GOFMAN",
    "Foyer de vie",
    "EHPAD Sainte-Emilie",
    "OCTO Technology",
    "Meetic",
    "Groupe ADP",
    "Bellerose",
    "RATP",
    "Digital Campus",
    "Xpansion",
    "Clinique de lEstree Stains",
    "Residence Les Vallieres",
    "Hopital Prive Jacques Cartier",
    "Hopital Leopold Bellan",
    "Hopital Europeen de Paris",
    "Artefact 3000",
    "65dBTBWA Groupe",
    "Colibri SAS Mano Mano",
    "Aria",
    "Publicis Conseil",
    "THI Factory",
    "ACCENTURE",
    "Hopital-Clinique Claude Bernard Metz",
    "Centre hospitalier Sud Francilien",
    "Effy Connect",
    "VICTOR and SIMON BV",
    "WAT - WE ARE TOGETHER",
    "TBWA Groupe",
    "Katchme",
    "LITTLE BIG CONNECTION",
    "SERVICES MARKETING DIVERSIFIES MARCEL",
    "EDENRED SA",
    "Ndoumbe",
    "AHSEEK",
    "Colibri SAS",
    "BNP Paribas SA",
    "FREE NOW",
    "SKELLO",
    "Steeve",
    "TF1",
    "DOCTOLIB",
    "Parlement Europeen Groupe Renew Europe",
    "Ledger SAS",
    "LOreal",
    "Television Francaise 1",
    "Griebasch",
    "LTU TECH",
    "Martin et Young",
    "QWINCY",
    "Irene Landou",
    "KONBINI",
    "lagence by wagd",
    "Societe Generale",
    "LUKO COVER",
    "EDENRED",
    "Television Francaise 1 - TF1",
    "Isobar France",
    "Christophe Olry",
    "DePUTe EUROPeEN",
    "Clinique Arago Paris",
    "GIE PRICEWATERHOUSECOOPERS SERVICES",
    "LOREAL",
    "SID LEE PARIS",
    "GROUPE LA CENTRALE",
    "UTA ",
    "LOreal",
    " LOreal",
    "EDENRED ",
    "INTRA DATA",
    "SERVICES MARKETING DIVERSIFIES",
    "LAGENCE BY WAGD",
    "Arneo Consulting",
    "Mateo",
    "StaffMe",
    "Binnov It SasuGIE PRICEWATERHOUSECOOPERS SERVICES",
    "STAFFME",
    "Native Communications",
    "Edenred ",
    "Free Now for Business",
    "MEETIC",
    "LOReAL",
    "Television Francaise 1",
    "E-TF1",
    "Steve",
    "Five Spirit",
    "Pricewater",
    "Edenred",
    "Spok",
    "SALES INTELLIGENCE",
    "Stink Studios Ltd",
    "BNP Paribas SA - Communication Groupe - 81396",
    "Ankorstore",
    "TBWA/Groupe",
    "SOCIETE GENERALE",
    "McCann-Erickson Paris",
    "TBWAGROUPE",
    "Ici Barbes",
    "Upfast",
    "CIFACOM",
    "Bellecour ecoles dart",
    "In Situ Training"
]

companies.each { |company|
	Logo.create(company: company, image: "")
}
